### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by 90636174** [react-native-org/react-native-appupgrade#3]
为什么npm下来的包缺少很多东西 没有安卓 ios 的依赖包，只有两个js

**Comment by hstarorg** [comment]
抱歉，该项目还没有正式发布到npm上，npm上那个现在只是一个占位。预计至本周内会完善文档，补充Demo，并更新到 `npm` 中。

**Comment by 90636174** [comment]
哦 好的

**Comment by hstarorg** [comment]
如果急需，可以直接copy 源代码。
